name: Test-Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.5

    - name: Install linter
      run: |
        go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
        echo "$HOME/go/bin" >> $GITHUB_PATH

    - name: Lint code
      run: golangci-lint run 

    - name: Run tests
      run: go test ./...

    
